default: &default
  adapter: postgresql 
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: posts_development 

test:
  <<: *default
  database: test_development

production:
  <<: *default
  database: production_development
